package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"main/graph/model"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.CreatePostPayload, error) {
	return r.postRepo.CreatePost(input)
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) (*model.PostsPayload, error) {
	return r.postRepo.GetPosts()
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, input model.PostFilter) (*model.PostPayload, error) {
	return r.postRepo.GetPost(input)
}
