// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       string `json:"id"`
	Body     string `json:"body"`
	ParentID int    `json:"parentID"`
}

type Mutation struct {
}

type Post struct {
	ID    string  `json:"id"`
	Title string  `json:"title"`
	Body  *string `json:"body,omitempty"`
}

type PostsFilter struct {
	IDIn []*int `json:"IDIn,omitempty"`
}

type PostsPayload struct {
	Posts []*Post `json:"posts,omitempty"`
}

type Query struct {
}

type CreatePostInput struct {
	Title string  `json:"title"`
	Body  *string `json:"body,omitempty"`
}

type CreatePostPayload struct {
	Post *Post `json:"post"`
}

type DeletePostInput struct {
	PostID string `json:"postID"`
}

type DeletePostPayload struct {
	Success bool `json:"success"`
}

type UpdatePostInput struct {
	PostID string  `json:"postID"`
	Title  *string `json:"title,omitempty"`
	Body   *string `json:"body,omitempty"`
}

type UpdatePostPayload struct {
	Post *Post `json:"post"`
}
