// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       int    `json:"id"`
	Body     string `json:"body"`
	ParentID int    `json:"parentID"`
}

type Mutation struct {
}

type Post struct {
	ID         int     `json:"id"`
	Title      string  `json:"title"`
	Body       *string `json:"body,omitempty"`
	CanComment bool    `json:"canComment"`
}

type PostFilter struct {
	IDIn int `json:"idIn"`
}

type PostPayload struct {
	Title    string     `json:"title"`
	Body     *string    `json:"body,omitempty"`
	Comments []*Comment `json:"comments,omitempty"`
}

type PostsPayload struct {
	Posts []*Post `json:"posts,omitempty"`
}

type Query struct {
}

type CreatePostInput struct {
	Title      string  `json:"title"`
	Body       *string `json:"body,omitempty"`
	CanComment bool    `json:"canComment"`
}

type CreatePostPayload struct {
	Post *Post `json:"post"`
}
